### ISSUE TITLE
images down for build instructions

### ISSUE THREAD

**Issue by philj0st** [darthcloud/cube64-dx#11]
Hi,
it seems the images are down over at [google code wiki](https://code.google.com/archive/p/cube64-dx/wikis/BuildingAdapter.wiki).
Any chance you still have them? maybe copy paste the build steps in github wiki and add the images here?

Thanks a lot for the awesome work!
Phil

**Comment by darthcloud** [comment]
The instruction from the old wiki to not apply to the new version of the adaptor.

Checkout the schematic from the latest release:
https://github.com/darthcloud/cube64-dx/releases/tag/v3.1

For programming the PIC I suggest using a PICKit 3.

But if you really want to see the old instructions you can checkout tag v2.0:
https://github.com/darthcloud/cube64-dx/tree/v2.0

check folder wiki

**Comment by philj0st** [comment]
aaah I see .. thanks for your help. And sorry for the unneccessary issue then.

**Comment by darthcloud** [comment]
No worries
